apiVersion: v1
kind: Secret
metadata:
  name: ocr-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: 2e8817266261610810596a50b8f4a8c5
  AWS_REGION_NAME: us-east-1
  AWS_S3_ENDPOINT: http://paperless-minio:9000
  AWS_SECRET_ACCESS_KEY: a503071debfa3ac0c1de1cd79f
  PAPERMERGE__DATABASE__URL: postgresql://papermerge:pmg-secret@papermergedatabase:5432/papermerge
  PAPERMERGE__REDIS__URL: redis://papermerge-redis:6379/0
  PAPERMERGE__S3__BUCKET_NAME: papermerge
  OCR_WORKER_ARGS: "-Q ocr -c 2"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-worker
  labels:
    app: ocr-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocr-worker
  template:
    metadata:
      labels:
        app: ocr-worker
    spec:
      containers:
        - name: ocr-worker
          image: papermerge/ocrworker:0.3.1
          envFrom:
            - secretRef:
                name: ocr-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"