---
apiVersion: v1
kind: Secret
metadata:
  name: papermerge-secret
type: Opaque
stringData:
  PAPERMERGE_AUTH_USERNAME: admin
  PAPERMERGE_AUTH_PASSWORD: secret
  PAPERMERGE_DATABASE_URL: postgresql://papermerge:pmg-secret@papermerge-database:5432/papermerge
  PAPERMERGE_MAIN_MEDIA_ROOT: /var/media/pmg
  OCR_LANG_CODES: "eng,fra"
  PAPERMERGE_OCR_DEFAULT_LANG_CODE: "eng"
  PAPERMERGE_REDIS_URL: redis://papermerge-redis:6379/0
  PAPERMERGE_SECURITY_SECRET_KEY: 8aa9127e904324e1d93c2b68483a327c3b5be964dd161e3e4df8dbca0443ec21
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-app
  labels:
    app: papermerge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: papermerge
  template:
    metadata:
      labels:
        app: papermerge
    spec:
      containers:
        - name: papermerge
          image: papermerge/papermerge:3.3.1
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: papermerge-secret
          volumeMounts:
            - name: media-storage
              mountPath: /var/media/pmg
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: papermerge-media-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: papermerge-service
  labels:
    app: papermerge
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: papermerge
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: papermerge-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi