---
apiVersion: v1
kind: Secret
metadata:
  name: papermerge-secret
type: Opaque
stringData:
  PAPERMERGE__AUTH__USERNAME: admin
  PAPERMERGE__AUTH__PASSWORD: secret
  PAPERMERGE__DATABASE__URL: postgresql://papermerge:pmg-secret@papermerge-database:5432/papermerge
  PAPERMERGE__MAIN__MEDIA_ROOT: /var/media/pmg
  PAPERMERGE__OCR__LANG_CODES: "eng,fra"
  PAPERMERGE__OCR__DEFAULT_LANG_CODE: "eng"
  PAPERMERGE__REDIS__URL: redis://papermerge-redis:6379/0
  PAPERMERGE__SECURITY__SECRET_KEY: 8aa9127e904324e1d93c2b68483a327c3b5be964dd161e3e4df8dbca0443ec21
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-app
  labels:
    app: papermerge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: papermerge
  template:
    metadata:
      labels:
        app: papermerge
    spec:
      containers:
        - name: papermerge
          image: papermerge/papermerge:3.3.1
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: papermerge-secret
          volumeMounts:
            - name: media-storage
              mountPath: /var/media/pmg
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: s3-media-pv
---

apiVersion: v1
kind: Service
metadata:
  name: papermerge-service
  labels:
    app: papermerge
spec:
  type: LoadBalancer
  selector:
    app: papermerge
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80


---