apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData: 
  POSTGRES_DB: papermerge
  POSTGRES_USER: papermerge
  POSTGRES_PASSWORD: pmg-secret

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: papermerge-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge-postgres
  template:
    metadata:
      labels:
        app: papermerge-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: papermerge-postgres-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: papermerge-database
spec:
  selector:
      app: papermerge-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432