apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData: 
  POSTGRES_DB: papermerge
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: pmg-secret

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    tier: postgres
spec:
  selector:
      tier: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres 
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef: 
            name: postgres-secret
        volumeMounts: 
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pvc
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/postgres" 
