apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData: 
  POSTGRES_DB: papermerge
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: pmg-secret

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    tier: postgres
spec:
  selector:
      tier: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef: 
            name: postgres-secret
      volumes:
      - name: postgres-storage
        emptyDir: {}

