apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
stringData: 
  REDIS_HOST: redis
  REDIS_HOST_PORT: "6379"

--- 

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    tier: redis
spec:
  selector:
      tier: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        envFrom:
        - secretRef: 
            name: redis-secret

