apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    tier: postgres
spec:
  selector:
      tier: papermerge-app
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

--- 

