apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    tier: papermerge-app
spec:
  selector:
      tier: papermerge-app
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP